#!/bin/bash
rm build.log
SRCDIR=src
SRCS=$(find $SRCDIR -name *.cpp)
g++ -c $SRCS -I src -I src/headers -I /usr/include/SFML-w -ldl -g -Wall -Wextra -Werror -pedantic &>> build.log
g++ -O *.o lib/glad/glad.o -o "Space Exploration" -I src/source -I src/headers -I /usr/include/SFML -lsfml-graphics -lsfml-window -lsfml-system -ldl -g -Wall -Wextra -Werror -pedantic &>> build.log
mkdir -p out &>> build.log
mv "Space Exploration" out &>> build.log
rm *.o &>> build.log
cp assets out -r &>> build.log
if [ ! -s build.log ]
then rm build.log
fi
